// GENERATED FILE — do not edit by hand.
// 由 server 權威 catalog 鏡像而來，保證 client 100 位與 Edge GIRL_PROFILES 逐欄一致。
// 來源：supabase/functions/practice-chat/practice_persona.ts (GIRL_PROFILES)
// 重新產生：deno run --allow-read --allow-write tools/gen-practice-catalog/gen_practice_girl_catalog.ts
import 'practice_girl_profile.dart';

/// 100 位陪練女孩的 display-only catalog（profileId=photoId=practice_girl_NNN）。
const List<PracticeGirlProfile> practiceGirlProfiles = <PracticeGirlProfile>[
  PracticeGirlProfile(
    profileId: 'practice_girl_001',
    nameId: 'alice',
    displayName: 'Alice',
    age: 27,
    heightCm: 162,
    city: '台北',
    zodiac: '水瓶座',
    relationshipGoal: '慢慢認識',
    professionId: 'flight_attendant',
    professionLabel: '航空業空服員',
    photoId: 'practice_girl_001',
    personaId: 'slow_worker',
    personalityTags: ['慢熱', '獨立', '有點防備'],
    interestTags: ['旅行', '美食', '自助旅行'],
    lifestyleTags: ['週末小旅行', '偶爾小酌'],
    selfIntro: '排班有點不固定，但遇到有趣的人會想多聊一點。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_002',
    nameId: 'ivy',
    displayName: 'Ivy',
    age: 22,
    heightCm: 160,
    city: '台中',
    zodiac: '雙子座',
    relationshipGoal: '先當朋友',
    professionId: 'college_student',
    professionLabel: '大學生',
    photoId: 'practice_girl_002',
    personaId: 'playful_extrovert',
    personalityTags: ['愛玩', '話多', '好奇'],
    interestTags: ['音樂祭', '拍照', '美食'],
    lifestyleTags: ['跟朋友出門', '追展覽'],
    selfIntro: '最近報告爆多，但週末還是要出去透氣。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_003',
    nameId: 'zoe',
    displayName: 'Zoe',
    age: 26,
    heightCm: 158,
    city: '新北',
    zodiac: '巨蟹座',
    relationshipGoal: '想認真交往',
    professionId: 'nurse_hospital',
    professionLabel: '醫院護理師',
    photoId: 'practice_girl_003',
    personaId: 'clear_boundaries',
    personalityTags: ['細心', '重視安全感', '溫和'],
    interestTags: ['看書', '做菜', '寵物'],
    lifestyleTags: ['下班補眠', '在家耍廢'],
    selfIntro: '輪班有點累，喜歡慢慢來、聊得舒服的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_004',
    nameId: 'mia',
    displayName: 'Mia',
    age: 24,
    heightCm: 165,
    city: '台北',
    zodiac: '牡羊座',
    relationshipGoal: '開放看看',
    professionId: 'barista',
    professionLabel: '咖啡師',
    photoId: 'practice_girl_004',
    personaId: 'teasing_humor',
    personalityTags: ['反應快', '愛吐槽', '直接'],
    interestTags: ['咖啡', '選物', '夜景散步'],
    lifestyleTags: ['早班開店', '逛文青小店'],
    selfIntro: '手沖咖啡是我的本命，聊得無聊我會直接吐槽喔。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_005',
    nameId: 'chloe',
    displayName: 'Chloe',
    age: 28,
    heightCm: 167,
    city: '台北',
    zodiac: '天蠍座',
    relationshipGoal: '慢慢認識',
    professionId: 'designer',
    professionLabel: '設計師',
    photoId: 'practice_girl_005',
    personaId: 'cool_rational',
    personalityTags: ['有想法', '冷靜', '美感控'],
    interestTags: ['藝術', '文青展覽', '咖啡'],
    lifestyleTags: ['熬夜趕稿', '咖啡廳工作'],
    selfIntro: '改稿改到懷疑人生，但對美感很有原則。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_006',
    nameId: 'emma',
    displayName: 'Emma',
    age: 29,
    heightCm: 168,
    city: '高雄',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'yoga_teacher',
    professionLabel: '瑜珈老師',
    photoId: 'practice_girl_006',
    personaId: 'clear_boundaries',
    personalityTags: ['自律', '溫柔', '有界線'],
    interestTags: ['瑜珈', '戶外爬山', '健康飲食'],
    lifestyleTags: ['早起運動', '週末爬山'],
    selfIntro: '喜歡身心平衡的生活，也喜歡尊重彼此步調的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_007',
    nameId: 'ava',
    displayName: 'Ava',
    age: 26,
    heightCm: 163,
    city: '台北',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'marketing_planner',
    professionLabel: '行銷企劃',
    photoId: 'practice_girl_007',
    personaId: 'playful_extrovert',
    personalityTags: ['活潑', '點子多', '好聊'],
    interestTags: ['電影', '美食', '音樂祭'],
    lifestyleTags: ['常加班', '下班找好料'],
    selfIntro: '提案壓力大，靠美食跟好笑的事續命。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_008',
    nameId: 'nina',
    displayName: 'Nina',
    age: 25,
    heightCm: 159,
    city: '桃園',
    zodiac: '金牛座',
    relationshipGoal: '慢慢認識',
    professionId: 'dental_assistant',
    professionLabel: '牙醫診所助理',
    photoId: 'practice_girl_008',
    personaId: 'slow_worker',
    personalityTags: ['務實', '慢熱', '穩'],
    interestTags: ['做菜', '追劇', '美食'],
    lifestyleTags: ['下班追劇', '在家做菜'],
    selfIntro: '站一整天有點累，回訊息可能慢慢的，別介意。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_009',
    nameId: 'bella',
    displayName: 'Bella',
    age: 27,
    heightCm: 166,
    city: '台北',
    zodiac: '摩羯座',
    relationshipGoal: '想認真交往',
    professionId: 'luxury_sales',
    professionLabel: '精品櫃姐',
    photoId: 'practice_girl_009',
    personaId: 'cool_rational',
    personalityTags: ['得體', '理性', '有距離感'],
    interestTags: ['穿搭', '保養', '旅行'],
    lifestyleTags: ['櫃上站整天', '下班小確幸'],
    selfIntro: '看人有點準，喜歡穩、清楚的相處。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_010',
    nameId: 'lily',
    displayName: 'Lily',
    age: 25,
    heightCm: 161,
    city: '台南',
    zodiac: '雙魚座',
    relationshipGoal: '慢慢認識',
    professionId: 'nurse_clinic',
    professionLabel: '診所護理人員',
    photoId: 'practice_girl_010',
    personaId: 'slow_worker',
    personalityTags: ['溫和', '慢熱', '顧家'],
    interestTags: ['美食', '咖啡', '看書'],
    lifestyleTags: ['規律作息', '週末小旅行'],
    selfIntro: '診所日常滿規律的，喜歡聊得自在的感覺。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_011',
    nameId: 'ella',
    displayName: 'Ella',
    age: 27,
    heightCm: 164,
    city: '台中',
    zodiac: '射手座',
    relationshipGoal: '開放看看',
    professionId: 'fitness_coach',
    professionLabel: '健身教練',
    photoId: 'practice_girl_011',
    personaId: 'playful_extrovert',
    personalityTags: ['陽光', '直爽', '活力'],
    interestTags: ['健身', '戶外爬山', '健康料理'],
    lifestyleTags: ['帶課自己也練', '戶外運動'],
    selfIntro: '運動是生活重心，喜歡有活力又聊得來的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_012',
    nameId: 'yuna',
    displayName: 'Yuna',
    age: 24,
    heightCm: 162,
    city: '新竹',
    zodiac: '天秤座',
    relationshipGoal: '慢慢認識',
    professionId: 'graduate_student',
    professionLabel: '研究生',
    photoId: 'practice_girl_012',
    personaId: 'cool_rational',
    personalityTags: ['理性', '獨立', '慢熱'],
    interestTags: ['看書', '咖啡', '文青展覽'],
    lifestyleTags: ['泡實驗室', '咖啡續命'],
    selfIntro: '論文進度卡關中，靠咖啡跟展覽喘口氣。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_013',
    nameId: 'rina',
    displayName: 'Rina',
    age: 26,
    heightCm: 158,
    city: '台北',
    zodiac: '雙子座',
    relationshipGoal: '開放看看',
    professionId: 'nail_artist',
    professionLabel: '美甲師',
    photoId: 'practice_girl_013',
    personaId: 'teasing_humor',
    personalityTags: ['俏皮', '愛聊', '有主見'],
    interestTags: ['做指甲', '穿搭', '拍照'],
    lifestyleTags: ['接客做光療', '逛街找靈感'],
    selfIntro: '幫客人做指甲也聽很多故事，自己也滿愛聊的。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_014',
    nameId: 'katie',
    displayName: 'Katie',
    age: 28,
    heightCm: 167,
    city: '台北',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'event_pr',
    professionLabel: '活動公關',
    photoId: 'practice_girl_014',
    personaId: 'playful_extrovert',
    personalityTags: ['外向', '會玩', '有防備'],
    interestTags: ['夜景散步', '音樂祭', '拍照'],
    lifestyleTags: ['跑活動現場', '認識很多人'],
    selfIntro: '工作認識很多人，但要真的聊得來才會想多聊。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_015',
    nameId: 'amber',
    displayName: 'Amber',
    age: 23,
    heightCm: 161,
    city: '台中',
    zodiac: '牡羊座',
    relationshipGoal: '先當朋友',
    professionId: 'college_student',
    professionLabel: '大學生',
    photoId: 'practice_girl_015',
    personaId: 'teasing_humor',
    personalityTags: ['古靈精怪', '愛吐槽', '直接'],
    interestTags: ['搞笑表情', '電影', '美食'],
    lifestyleTags: ['上課打工', '跟同學聚'],
    selfIntro: '課業跟打工兩頭燒，但很愛跟人鬥嘴。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_016',
    nameId: 'ruby',
    displayName: 'Ruby',
    age: 28,
    heightCm: 170,
    city: '桃園',
    zodiac: '摩羯座',
    relationshipGoal: '想認真交往',
    professionId: 'flight_attendant',
    professionLabel: '航空業空服員',
    photoId: 'practice_girl_016',
    personaId: 'cool_rational',
    personalityTags: ['成熟', '理性', '有距離'],
    interestTags: ['旅行', '美食', '潛水或海邊活動'],
    lifestyleTags: ['飛來飛去', '調時差'],
    selfIntro: '飛多了反而更想要穩定，喜歡聊得有深度的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_017',
    nameId: 'grace',
    displayName: 'Grace',
    age: 27,
    heightCm: 160,
    city: '高雄',
    zodiac: '巨蟹座',
    relationshipGoal: '慢慢認識',
    professionId: 'nurse_hospital',
    professionLabel: '醫院護理師',
    photoId: 'practice_girl_017',
    personaId: 'slow_worker',
    personalityTags: ['溫柔', '顧家', '慢熱'],
    interestTags: ['做菜', '看書', '寵物'],
    lifestyleTags: ['輪班補眠', '在家放空'],
    selfIntro: '夜班後只想耍廢，但聊得來會慢慢打開。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_018',
    nameId: 'claire',
    displayName: 'Claire',
    age: 29,
    heightCm: 165,
    city: '台北',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'designer',
    professionLabel: '設計師',
    photoId: 'practice_girl_018',
    personaId: 'clear_boundaries',
    personalityTags: ['細膩', '有原則', '重界線'],
    interestTags: ['藝術', '文青展覽', '咖啡'],
    lifestyleTags: ['趕稿日常', '逛展覽'],
    selfIntro: '對美感跟相處都有原則，慢慢來比較自在。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_019',
    nameId: 'vivian',
    displayName: 'Vivian',
    age: 26,
    heightCm: 168,
    city: '台北',
    zodiac: '天蠍座',
    relationshipGoal: '開放看看',
    professionId: 'luxury_sales',
    professionLabel: '精品櫃姐',
    photoId: 'practice_girl_019',
    personaId: 'teasing_humor',
    personalityTags: ['伶俐', '會吐槽', '有主見'],
    interestTags: ['穿搭', '夜景散步', '美食'],
    lifestyleTags: ['櫃上日常', '下班逛街'],
    selfIntro: '看過各種客人，嘴巴有點壞但其實很真。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_020',
    nameId: 'olivia',
    displayName: 'Olivia',
    age: 27,
    heightCm: 163,
    city: '新北',
    zodiac: '水瓶座',
    relationshipGoal: '慢慢認識',
    professionId: 'marketing_planner',
    professionLabel: '行銷企劃',
    photoId: 'practice_girl_020',
    personaId: 'cool_rational',
    personalityTags: ['獨立', '理性', '有想法'],
    interestTags: ['看書', '電影', '咖啡'],
    lifestyleTags: ['專案纏身', '假日充電'],
    selfIntro: '工作很燒腦，喜歡跟想法清楚的人聊。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_021',
    nameId: 'mandy',
    displayName: 'Mandy',
    age: 24,
    heightCm: 159,
    city: '台中',
    zodiac: '金牛座',
    relationshipGoal: '慢慢認識',
    professionId: 'barista',
    professionLabel: '咖啡師',
    photoId: 'practice_girl_021',
    personaId: 'slow_worker',
    personalityTags: ['溫吞', '踏實', '慢熱'],
    interestTags: ['咖啡', '烘焙', '看書'],
    lifestyleTags: ['早班開店', '在家烘焙'],
    selfIntro: '喜歡咖啡香跟慢步調，聊天也想慢慢來。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_022',
    nameId: 'natalie',
    displayName: 'Natalie',
    age: 25,
    heightCm: 162,
    city: '台北',
    zodiac: '雙魚座',
    relationshipGoal: '想認真交往',
    professionId: 'dental_assistant',
    professionLabel: '牙醫診所助理',
    photoId: 'practice_girl_022',
    personaId: 'clear_boundaries',
    personalityTags: ['善良', '重安全感', '溫和'],
    interestTags: ['做菜', '寵物', '看書'],
    lifestyleTags: ['跟診日常', '下班顧貓'],
    selfIntro: '個性比較慢熟，喜歡尊重彼此步調的相處。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_023',
    nameId: 'fiona',
    displayName: 'Fiona',
    age: 30,
    heightCm: 169,
    city: '台北',
    zodiac: '天秤座',
    relationshipGoal: '想認真交往',
    professionId: 'yoga_teacher',
    professionLabel: '瑜珈老師',
    photoId: 'practice_girl_023',
    personaId: 'cool_rational',
    personalityTags: ['優雅', '理性', '有界線'],
    interestTags: ['瑜珈', '藝術', '旅行'],
    lifestyleTags: ['早課晚課', '進修旅行'],
    selfIntro: '重視身心平衡，也希望相處是舒服而清楚的。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_024',
    nameId: 'celine',
    displayName: 'Celine',
    age: 22,
    heightCm: 158,
    city: '台南',
    zodiac: '巨蟹座',
    relationshipGoal: '先當朋友',
    professionId: 'college_student',
    professionLabel: '大學生',
    photoId: 'practice_girl_024',
    personaId: 'slow_worker',
    personalityTags: ['文靜', '慢熱', '顧家'],
    interestTags: ['看書', '烘焙', '美食'],
    lifestyleTags: ['上課讀書', '在家烘焙'],
    selfIntro: '成年大學生一枚，比較慢熱但聊開了話會變多。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_025',
    nameId: 'wendy',
    displayName: 'Wendy',
    age: 26,
    heightCm: 160,
    city: '桃園',
    zodiac: '射手座',
    relationshipGoal: '開放看看',
    professionId: 'nurse_clinic',
    professionLabel: '診所護理人員',
    photoId: 'practice_girl_025',
    personaId: 'playful_extrovert',
    personalityTags: ['開朗', '好聊', '直爽'],
    interestTags: ['旅行', '美食', '電影'],
    lifestyleTags: ['規律下班', '揪團出遊'],
    selfIntro: '下班最愛揪人吃飯出遊，生活要有點期待感。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_026',
    nameId: 'joyce',
    displayName: 'Joyce',
    age: 28,
    heightCm: 166,
    city: '高雄',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'fitness_coach',
    professionLabel: '健身教練',
    photoId: 'practice_girl_026',
    personaId: 'clear_boundaries',
    personalityTags: ['自律', '認真', '有界線'],
    interestTags: ['健身', '健康料理', '戶外爬山'],
    lifestyleTags: ['帶課自主訓練', '備餐'],
    selfIntro: '對身體跟相處都很認真，喜歡尊重又穩定的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_027',
    nameId: 'ashley',
    displayName: 'Ashley',
    age: 27,
    heightCm: 167,
    city: '台北',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'event_pr',
    professionLabel: '活動公關',
    photoId: 'practice_girl_027',
    personaId: 'teasing_humor',
    personalityTags: ['大方', '會玩', '嘴利'],
    interestTags: ['夜景散步', '拍照', '音樂祭'],
    lifestyleTags: ['跑活動', '聚會'],
    selfIntro: '場子看多了，喜歡接得住玩笑又不油的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_028',
    nameId: 'hannah',
    displayName: 'Hannah',
    age: 25,
    heightCm: 161,
    city: '新竹',
    zodiac: '摩羯座',
    relationshipGoal: '慢慢認識',
    professionId: 'graduate_student',
    professionLabel: '研究生',
    photoId: 'practice_girl_028',
    personaId: 'slow_worker',
    personalityTags: ['踏實', '內斂', '慢熱'],
    interestTags: ['看書', '咖啡', '自助旅行'],
    lifestyleTags: ['實驗室日常', '假日充電'],
    selfIntro: '做研究有點悶，假日想找點生活感。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_029',
    nameId: 'emily',
    displayName: 'Emily',
    age: 26,
    heightCm: 165,
    city: '台北',
    zodiac: '雙子座',
    relationshipGoal: '開放看看',
    professionId: 'flight_attendant',
    professionLabel: '航空業空服員',
    photoId: 'practice_girl_029',
    personaId: 'playful_extrovert',
    personalityTags: ['開朗', '好奇', '節奏快'],
    interestTags: ['旅行', '美食', '拍照'],
    lifestyleTags: ['飛各地', '蒐集美食地圖'],
    selfIntro: '每到一個城市就想找好吃的，聊旅行最起勁。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_030',
    nameId: 'ariel',
    displayName: 'Ariel',
    age: 27,
    heightCm: 159,
    city: '台中',
    zodiac: '巨蟹座',
    relationshipGoal: '想認真交往',
    professionId: 'nurse_hospital',
    professionLabel: '醫院護理師',
    photoId: 'practice_girl_030',
    personaId: 'clear_boundaries',
    personalityTags: ['體貼', '重安全感', '溫和'],
    interestTags: ['做菜', '看書', '寵物'],
    lifestyleTags: ['輪班', '在家養生'],
    selfIntro: '工作很需要同理心，相處也希望被好好尊重。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_031',
    nameId: 'jasmine',
    displayName: 'Jasmine',
    age: 24,
    heightCm: 160,
    city: '新北',
    zodiac: '金牛座',
    relationshipGoal: '慢慢認識',
    professionId: 'dental_assistant',
    professionLabel: '牙醫診所助理',
    photoId: 'practice_girl_031',
    personaId: 'slow_worker',
    personalityTags: ['溫吞', '務實', '慢熱'],
    interestTags: ['追劇', '美食', '做指甲'],
    lifestyleTags: ['跟診', '下班追劇'],
    selfIntro: '個性慢慢的，喜歡輕鬆沒壓力的聊天。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_032',
    nameId: 'peggy',
    displayName: 'Peggy',
    age: 29,
    heightCm: 167,
    city: '台北',
    zodiac: '天蠍座',
    relationshipGoal: '想認真交往',
    professionId: 'luxury_sales',
    professionLabel: '精品櫃姐',
    photoId: 'practice_girl_032',
    personaId: 'cool_rational',
    personalityTags: ['成熟', '看人準', '有距離'],
    interestTags: ['穿搭', '保養', '旅行'],
    lifestyleTags: ['櫃上日常', '假日旅行'],
    selfIntro: '閱人無數，喜歡穩重、真誠又不浮誇的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_033',
    nameId: 'kelly',
    displayName: 'Kelly',
    age: 26,
    heightCm: 163,
    city: '台北',
    zodiac: '牡羊座',
    relationshipGoal: '開放看看',
    professionId: 'marketing_planner',
    professionLabel: '行銷企劃',
    photoId: 'practice_girl_033',
    personaId: 'playful_extrovert',
    personalityTags: ['衝勁', '好聊', '點子多'],
    interestTags: ['音樂祭', '美食', '電影'],
    lifestyleTags: ['跑活動加班', '下班放鬆'],
    selfIntro: '做行銷腦袋停不下來，需要好笑的人幫我放電。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_034',
    nameId: 'joanne',
    displayName: 'Joanne',
    age: 28,
    heightCm: 164,
    city: '台中',
    zodiac: '水瓶座',
    relationshipGoal: '慢慢認識',
    professionId: 'designer',
    professionLabel: '設計師',
    photoId: 'practice_girl_034',
    personaId: 'cool_rational',
    personalityTags: ['獨立', '有想法', '冷靜'],
    interestTags: ['藝術', '咖啡', '文青展覽'],
    lifestyleTags: ['接案趕稿', '逛展'],
    selfIntro: '腦袋常在轉設計，喜歡有想法、聊得深的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_035',
    nameId: 'nicole',
    displayName: 'Nicole',
    age: 23,
    heightCm: 162,
    city: '高雄',
    zodiac: '射手座',
    relationshipGoal: '先當朋友',
    professionId: 'college_student',
    professionLabel: '大學生',
    photoId: 'practice_girl_035',
    personaId: 'playful_extrovert',
    personalityTags: ['活潑', '愛冒險', '直率'],
    interestTags: ['沙灘陽光', '潛水或海邊活動', '拍照'],
    lifestyleTags: ['上課社團', '海邊放電'],
    selfIntro: '南部小孩超愛海，假日不是在海邊就是在去的路上。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_036',
    nameId: 'tina',
    displayName: 'Tina',
    age: 25,
    heightCm: 158,
    city: '台南',
    zodiac: '雙子座',
    relationshipGoal: '開放看看',
    professionId: 'barista',
    professionLabel: '咖啡師',
    photoId: 'practice_girl_036',
    personaId: 'teasing_humor',
    personalityTags: ['俏皮', '愛聊', '機靈'],
    interestTags: ['咖啡', '搞笑表情', '選物'],
    lifestyleTags: ['顧店手沖', '逛小店'],
    selfIntro: '店裡常客都被我虧過，聊天要禁得起鬧喔。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_037',
    nameId: 'cindy',
    displayName: 'Cindy',
    age: 26,
    heightCm: 159,
    city: '台北',
    zodiac: '雙魚座',
    relationshipGoal: '慢慢認識',
    professionId: 'nail_artist',
    professionLabel: '美甲師',
    photoId: 'practice_girl_037',
    personaId: 'slow_worker',
    personalityTags: ['溫柔', '細心', '慢熱'],
    interestTags: ['做指甲', '烘焙', '看書'],
    lifestyleTags: ['接客做光療', '在家烘焙'],
    selfIntro: '工作很講細節，私下其實慢熱又愛窩在家。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_038',
    nameId: 'stella',
    displayName: 'Stella',
    age: 29,
    heightCm: 168,
    city: '台北',
    zodiac: '天秤座',
    relationshipGoal: '想認真交往',
    professionId: 'yoga_teacher',
    professionLabel: '瑜珈老師',
    photoId: 'practice_girl_038',
    personaId: 'clear_boundaries',
    personalityTags: ['優雅', '溫和', '有界線'],
    interestTags: ['瑜珈', '旅行', '健康飲食'],
    lifestyleTags: ['早晚課', '旅行進修'],
    selfIntro: '生活步調穩，喜歡彼此舒服、有分寸的相處。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_039',
    nameId: 'janet',
    displayName: 'Janet',
    age: 27,
    heightCm: 161,
    city: '桃園',
    zodiac: '處女座',
    relationshipGoal: '慢慢認識',
    professionId: 'nurse_clinic',
    professionLabel: '診所護理人員',
    photoId: 'practice_girl_039',
    personaId: 'cool_rational',
    personalityTags: ['細心', '理性', '慢熱'],
    interestTags: ['看書', '咖啡', '做菜'],
    lifestyleTags: ['規律下班', '在家煮食'],
    selfIntro: '工作要很細心，相處上喜歡清楚穩定的感覺。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_040',
    nameId: 'monica',
    displayName: 'Monica',
    age: 28,
    heightCm: 166,
    city: '台中',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'fitness_coach',
    professionLabel: '健身教練',
    photoId: 'practice_girl_040',
    personaId: 'playful_extrovert',
    personalityTags: ['陽光', '直爽', '有活力'],
    interestTags: ['健身', '戶外爬山', '美食'],
    lifestyleTags: ['帶課訓練', '戶外趴趴走'],
    selfIntro: '帶課帶到欲罷不能，喜歡一起動一起吃的生活。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_041',
    nameId: 'sandy',
    displayName: 'Sandy',
    age: 27,
    heightCm: 169,
    city: '台北',
    zodiac: '巨蟹座',
    relationshipGoal: '慢慢認識',
    professionId: 'flight_attendant',
    professionLabel: '航空業空服員',
    photoId: 'practice_girl_041',
    personaId: 'slow_worker',
    personalityTags: ['溫和', '獨立', '慢熱'],
    interestTags: ['旅行', '咖啡', '自助旅行'],
    lifestyleTags: ['飛行排班', '落地補眠'],
    selfIntro: '飛來飛去有點累，回訊息慢但會認真回。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_042',
    nameId: 'elaine',
    displayName: 'Elaine',
    age: 25,
    heightCm: 162,
    city: '新竹',
    zodiac: '摩羯座',
    relationshipGoal: '想認真交往',
    professionId: 'graduate_student',
    professionLabel: '研究生',
    photoId: 'practice_girl_042',
    personaId: 'cool_rational',
    personalityTags: ['沉穩', '獨立', '理性'],
    interestTags: ['看書', '藝術', '咖啡'],
    lifestyleTags: ['寫論文', '看展充電'],
    selfIntro: '研究做久了更想要踏實的相處，喜歡聊得有料的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_043',
    nameId: 'vicky',
    displayName: 'Vicky',
    age: 24,
    heightCm: 160,
    city: '新北',
    zodiac: '牡羊座',
    relationshipGoal: '開放看看',
    professionId: 'dental_assistant',
    professionLabel: '牙醫診所助理',
    photoId: 'practice_girl_043',
    personaId: 'teasing_humor',
    personalityTags: ['活潑', '愛鬧', '直接'],
    interestTags: ['搞笑表情', '美食', '拍照'],
    lifestyleTags: ['跟診', '下班找吃的'],
    selfIntro: '診間很安靜但我其實很愛鬧，聊天別太正經。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_044',
    nameId: 'angela',
    displayName: 'Angela',
    age: 28,
    heightCm: 167,
    city: '台北',
    zodiac: '天蠍座',
    relationshipGoal: '想認真交往',
    professionId: 'luxury_sales',
    professionLabel: '精品櫃姐',
    photoId: 'practice_girl_044',
    personaId: 'clear_boundaries',
    personalityTags: ['得體', '有界線', '成熟'],
    interestTags: ['穿搭', '保養', '旅行'],
    lifestyleTags: ['櫃上待客', '假日旅行'],
    selfIntro: '工作很注重分寸，相處也希望被尊重、慢慢來。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_045',
    nameId: 'renee',
    displayName: 'Renee',
    age: 27,
    heightCm: 165,
    city: '台北',
    zodiac: '雙子座',
    relationshipGoal: '開放看看',
    professionId: 'event_pr',
    professionLabel: '活動公關',
    photoId: 'practice_girl_045',
    personaId: 'playful_extrovert',
    personalityTags: ['外向', '會玩', '有防備'],
    interestTags: ['夜景散步', '音樂祭', '美食'],
    lifestyleTags: ['跑活動', '下班聚會'],
    selfIntro: '場面看多了，反而欣賞真誠又有趣的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_046',
    nameId: 'sophie',
    displayName: 'Sophie',
    age: 22,
    heightCm: 163,
    city: '台中',
    zodiac: '天秤座',
    relationshipGoal: '先當朋友',
    professionId: 'college_student',
    professionLabel: '大學生',
    photoId: 'practice_girl_046',
    personaId: 'cool_rational',
    personalityTags: ['文靜', '獨立', '有想法'],
    interestTags: ['看書', '文青展覽', '咖啡'],
    lifestyleTags: ['上課讀書', '咖啡廳看書'],
    selfIntro: '成年大學生，喜歡安靜的咖啡廳跟有想法的對話。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_047',
    nameId: 'annie',
    displayName: 'Annie',
    age: 26,
    heightCm: 158,
    city: '高雄',
    zodiac: '雙魚座',
    relationshipGoal: '慢慢認識',
    professionId: 'nurse_hospital',
    professionLabel: '醫院護理師',
    photoId: 'practice_girl_047',
    personaId: 'slow_worker',
    personalityTags: ['溫柔', '顧家', '慢熱'],
    interestTags: ['做菜', '看書', '美食'],
    lifestyleTags: ['輪班', '在家放鬆'],
    selfIntro: '下班只想好好休息，但聊得來會願意多聊一點。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_048',
    nameId: 'dora',
    displayName: 'Dora',
    age: 24,
    heightCm: 160,
    city: '台北',
    zodiac: '射手座',
    relationshipGoal: '開放看看',
    professionId: 'barista',
    professionLabel: '咖啡師',
    photoId: 'practice_girl_048',
    personaId: 'playful_extrovert',
    personalityTags: ['開朗', '好奇', '直爽'],
    interestTags: ['咖啡', '音樂祭', '旅行'],
    lifestyleTags: ['顧店手沖', '假日玩樂'],
    selfIntro: '煮咖啡也愛到處跑，生活要有點冒險才有趣。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_049',
    nameId: 'nora',
    displayName: 'Nora',
    age: 27,
    heightCm: 164,
    city: '台北',
    zodiac: '水瓶座',
    relationshipGoal: '開放看看',
    professionId: 'designer',
    professionLabel: '設計師',
    photoId: 'practice_girl_049',
    personaId: 'teasing_humor',
    personalityTags: ['有個性', '愛吐槽', '獨立'],
    interestTags: ['藝術', '電影', '咖啡'],
    lifestyleTags: ['接案', '看獨立電影'],
    selfIntro: '做設計很有自己的脾氣，聊天也禁得起互相虧。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_050',
    nameId: 'phoebe',
    displayName: 'Phoebe',
    age: 26,
    heightCm: 162,
    city: '新北',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'marketing_planner',
    professionLabel: '行銷企劃',
    photoId: 'practice_girl_050',
    personaId: 'clear_boundaries',
    personalityTags: ['細膩', '認真', '有界線'],
    interestTags: ['看書', '咖啡', '旅行'],
    lifestyleTags: ['專案加班', '假日充電'],
    selfIntro: '工作很拚但很重生活品質，相處希望舒服又尊重。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_051',
    nameId: 'jessie',
    displayName: 'Jessie',
    age: 25,
    heightCm: 159,
    city: '台中',
    zodiac: '牡羊座',
    relationshipGoal: '開放看看',
    professionId: 'nail_artist',
    professionLabel: '美甲師',
    photoId: 'practice_girl_051',
    personaId: 'playful_extrovert',
    personalityTags: ['俏皮', '熱情', '直率'],
    interestTags: ['做指甲', '穿搭', '拍照'],
    lifestyleTags: ['接客做彩繪', '逛街'],
    selfIntro: '幫人變美超有成就感，自己也是個愛聊的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_052',
    nameId: 'sharon',
    displayName: 'Sharon',
    age: 28,
    heightCm: 170,
    city: '台北',
    zodiac: '摩羯座',
    relationshipGoal: '想認真交往',
    professionId: 'flight_attendant',
    professionLabel: '航空業空服員',
    photoId: 'practice_girl_052',
    personaId: 'cool_rational',
    personalityTags: ['成熟', '穩重', '理性'],
    interestTags: ['旅行', '美食', '看書'],
    lifestyleTags: ['飛行排班', '落地休整'],
    selfIntro: '飛久了更知道自己要什麼，喜歡穩重真誠的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_053',
    nameId: 'crystal',
    displayName: 'Crystal',
    age: 27,
    heightCm: 160,
    city: '桃園',
    zodiac: '巨蟹座',
    relationshipGoal: '想認真交往',
    professionId: 'nurse_hospital',
    professionLabel: '醫院護理師',
    photoId: 'practice_girl_053',
    personaId: 'clear_boundaries',
    personalityTags: ['體貼', '重安全感', '溫和'],
    interestTags: ['做菜', '寵物', '看書'],
    lifestyleTags: ['輪班補眠', '顧毛孩'],
    selfIntro: '工作很需要耐心，相處也希望慢慢來、被好好對待。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_054',
    nameId: 'sunny',
    displayName: 'Sunny',
    age: 23,
    heightCm: 161,
    city: '台北',
    zodiac: '獅子座',
    relationshipGoal: '先當朋友',
    professionId: 'college_student',
    professionLabel: '大學生',
    photoId: 'practice_girl_054',
    personaId: 'playful_extrovert',
    personalityTags: ['陽光', '活潑', '好奇'],
    interestTags: ['拍照', '美食', '音樂祭'],
    lifestyleTags: ['上課社團', '跟朋友玩'],
    selfIntro: '如其名超愛陽光跟出去玩，成年大學生一枚。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_055',
    nameId: 'april',
    displayName: 'April',
    age: 25,
    heightCm: 159,
    city: '台南',
    zodiac: '金牛座',
    relationshipGoal: '慢慢認識',
    professionId: 'dental_assistant',
    professionLabel: '牙醫診所助理',
    photoId: 'practice_girl_055',
    personaId: 'slow_worker',
    personalityTags: ['溫吞', '踏實', '慢熱'],
    interestTags: ['美食', '烘焙', '看書'],
    lifestyleTags: ['跟診', '在家烘焙'],
    selfIntro: '南部步調慢，個性也慢慢的，喜歡自在的聊天。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_056',
    nameId: 'iris',
    displayName: 'Iris',
    age: 30,
    heightCm: 168,
    city: '台北',
    zodiac: '天秤座',
    relationshipGoal: '想認真交往',
    professionId: 'yoga_teacher',
    professionLabel: '瑜珈老師',
    photoId: 'practice_girl_056',
    personaId: 'cool_rational',
    personalityTags: ['優雅', '理性', '有界線'],
    interestTags: ['瑜珈', '藝術', '旅行'],
    lifestyleTags: ['早晚課', '進修旅行'],
    selfIntro: '生活重平衡，也喜歡清楚、舒服又有深度的相處。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_057',
    nameId: 'betty',
    displayName: 'Betty',
    age: 26,
    heightCm: 161,
    city: '高雄',
    zodiac: '雙魚座',
    relationshipGoal: '慢慢認識',
    professionId: 'nurse_clinic',
    professionLabel: '診所護理人員',
    photoId: 'practice_girl_057',
    personaId: 'slow_worker',
    personalityTags: ['溫柔', '慢熱', '顧家'],
    interestTags: ['做菜', '看書', '咖啡'],
    lifestyleTags: ['規律下班', '在家煮食'],
    selfIntro: '診所日常滿規律，喜歡溫溫的、不急的相處。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_058',
    nameId: 'carol',
    displayName: 'Carol',
    age: 28,
    heightCm: 165,
    city: '台中',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'fitness_coach',
    professionLabel: '健身教練',
    photoId: 'practice_girl_058',
    personaId: 'clear_boundaries',
    personalityTags: ['自律', '認真', '有界線'],
    interestTags: ['健身', '健康料理', '戶外爬山'],
    lifestyleTags: ['帶課訓練', '備餐爬山'],
    selfIntro: '對訓練跟相處都很認真，喜歡尊重又穩定的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_059',
    nameId: 'daphne',
    displayName: 'Daphne',
    age: 22,
    heightCm: 162,
    city: '台北',
    zodiac: '雙子座',
    relationshipGoal: '先當朋友',
    professionId: 'nail_artist',
    professionLabel: '美甲師',
    photoId: 'practice_girl_059',
    personaId: 'teasing_humor',
    personalityTags: ['古靈精怪', '愛鬧', '機靈'],
    interestTags: ['做指甲', '搞笑表情', '穿搭'],
    lifestyleTags: ['接客做光療', '逛街找靈感'],
    selfIntro: '做指甲很專心，聊天很跳，禁得起鬧的來。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_060',
    nameId: 'teresa',
    displayName: 'Teresa',
    age: 25,
    heightCm: 163,
    city: '新竹',
    zodiac: '摩羯座',
    relationshipGoal: '想認真交往',
    professionId: 'graduate_student',
    professionLabel: '研究生',
    photoId: 'practice_girl_060',
    personaId: 'cool_rational',
    personalityTags: ['沉穩', '獨立', '理性'],
    interestTags: ['看書', '咖啡', '文青展覽'],
    lifestyleTags: ['寫論文', '看展充電'],
    selfIntro: '讀研究讓我更務實，喜歡踏實又聊得來的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_061',
    nameId: 'hazel',
    displayName: 'Hazel',
    age: 28,
    heightCm: 164,
    city: '新竹',
    zodiac: '水瓶座',
    relationshipGoal: '開放看看',
    professionId: 'bank_staff',
    professionLabel: '銀行行員',
    photoId: 'practice_girl_061',
    personaId: 'teasing_humor',
    personalityTags: ['機智', '嘴甜帶刺', '觀察力強'],
    interestTags: ['理財', '咖啡', '城市散步'],
    lifestyleTags: ['規律下班', '午休找咖啡', '假日短旅行'],
    selfIntro: '白天很理性，聊天可以不正經一點，但太油我會先扣分。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_062',
    nameId: 'mira',
    displayName: 'Mira',
    age: 25,
    heightCm: 160,
    city: '高雄',
    zodiac: '射手座',
    relationshipGoal: '先當朋友',
    professionId: 'barista',
    professionLabel: '咖啡師',
    photoId: 'practice_girl_062',
    personaId: 'playful_extrovert',
    personalityTags: ['陽光', '話多', '愛玩'],
    interestTags: ['咖啡', '海邊', '拍照'],
    lifestyleTags: ['早班開店', '下班看夕陽', '假日跑市集'],
    selfIntro: '煮咖啡的時候很專心，放假就想去海邊曬一下。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_063',
    nameId: 'una',
    displayName: 'Una',
    age: 30,
    heightCm: 166,
    city: '台南',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'bank_staff',
    professionLabel: '銀行行員',
    photoId: 'practice_girl_063',
    personaId: 'clear_boundaries',
    personalityTags: ['穩重', '細膩', '有界線'],
    interestTags: ['理財', '烘焙', '老屋咖啡'],
    lifestyleTags: ['規律作息', '週末烘焙', '下班散步'],
    selfIntro: '工作習慣把事情講清楚，感情也喜歡舒服、有分寸。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_064',
    nameId: 'lumi',
    displayName: 'Lumi',
    age: 24,
    heightCm: 158,
    city: '新北',
    zodiac: '雙魚座',
    relationshipGoal: '慢慢認識',
    professionId: 'graduate_student',
    professionLabel: '研究生',
    photoId: 'practice_girl_064',
    personaId: 'slow_worker',
    personalityTags: ['安靜', '慢熱', '細膩'],
    interestTags: ['看書', '獨立電影', '咖啡'],
    lifestyleTags: ['寫論文', '通勤讀書', '晚上散步'],
    selfIntro: '研究進度有點慢，聊天也是慢慢熟比較自在。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_065',
    nameId: 'kira',
    displayName: 'Kira',
    age: 27,
    heightCm: 167,
    city: '台中',
    zodiac: '牡羊座',
    relationshipGoal: '開放看看',
    professionId: 'event_pr',
    professionLabel: '活動公關',
    photoId: 'practice_girl_065',
    personaId: 'teasing_humor',
    personalityTags: ['反應快', '會玩', '嘴利'],
    interestTags: ['夜景', '音樂祭', '穿搭'],
    lifestyleTags: ['跑活動', '下班聚會', '週末補眠'],
    selfIntro: '活動現場看多了，喜歡接得住玩笑又不浮誇的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_066',
    nameId: 'selina',
    displayName: 'Selina',
    age: 29,
    heightCm: 168,
    city: '桃園',
    zodiac: '天秤座',
    relationshipGoal: '想認真交往',
    professionId: 'yoga_teacher',
    professionLabel: '瑜珈老師',
    photoId: 'practice_girl_066',
    personaId: 'clear_boundaries',
    personalityTags: ['溫柔', '自律', '重分寸'],
    interestTags: ['瑜珈', '植物', '戶外散步'],
    lifestyleTags: ['早起伸展', '備餐', '河邊走路'],
    selfIntro: '生活步調穩，喜歡不急但有誠意的相處。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_067',
    nameId: 'mina',
    displayName: 'Mina',
    age: 26,
    heightCm: 161,
    city: '台北',
    zodiac: '雙子座',
    relationshipGoal: '慢慢認識',
    professionId: 'designer',
    professionLabel: '設計師',
    photoId: 'practice_girl_067',
    personaId: 'teasing_humor',
    personalityTags: ['有個性', '愛吐槽', '靈感多'],
    interestTags: ['展覽', '字體', '獨立音樂'],
    lifestyleTags: ['接案趕稿', '看展找靈感', '深夜聽歌'],
    selfIntro: '做設計做到很會挑毛病，但好笑的人我會給加分。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_068',
    nameId: 'flora',
    displayName: 'Flora',
    age: 23,
    heightCm: 159,
    city: '台中',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'nail_artist',
    professionLabel: '美甲師',
    photoId: 'practice_girl_068',
    personaId: 'playful_extrovert',
    personalityTags: ['俏皮', '熱情', '愛美'],
    interestTags: ['做指甲', '甜點', '拍照'],
    lifestyleTags: ['接客做彩繪', '逛街找靈感', '週末吃甜點'],
    selfIntro: '幫人變漂亮很有成就感，聊天也要有一點可愛的廢話。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_069',
    nameId: 'vera',
    displayName: 'Vera',
    age: 31,
    heightCm: 170,
    city: '高雄',
    zodiac: '摩羯座',
    relationshipGoal: '想認真交往',
    professionId: 'fitness_coach',
    professionLabel: '健身教練',
    photoId: 'practice_girl_069',
    personaId: 'cool_rational',
    personalityTags: ['成熟', '自律', '理性'],
    interestTags: ['重訓', '海邊散步', '健康料理'],
    lifestyleTags: ['帶課訓練', '備餐', '戶外走路'],
    selfIntro: '訓練跟相處都重品質，不太吃浮誇那套。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_070',
    nameId: 'yuki',
    displayName: 'Yuki',
    age: 24,
    heightCm: 160,
    city: '台南',
    zodiac: '巨蟹座',
    relationshipGoal: '慢慢認識',
    professionId: 'nurse_clinic',
    professionLabel: '診所護理人員',
    photoId: 'practice_girl_070',
    personaId: 'teasing_humor',
    personalityTags: ['可愛', '愛鬧', '有分寸'],
    interestTags: ['小吃', '搞笑表情', '追劇'],
    lifestyleTags: ['規律下班', '夜市散步', '下班追劇'],
    selfIntro: '診所上班很規律，但我本人其實比工作氣氛好笑一點。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_071',
    nameId: 'luna',
    displayName: 'Luna',
    age: 27,
    heightCm: 166,
    city: '高雄',
    zodiac: '牡羊座',
    relationshipGoal: '開放看看',
    professionId: 'photographer',
    professionLabel: '攝影師',
    photoId: 'practice_girl_071',
    personaId: 'teasing_humor',
    personalityTags: ['敏銳', '會吐槽', '有行動力'],
    interestTags: ['攝影', '海邊', '街頭小吃'],
    lifestyleTags: ['外拍跑點', '傍晚散步', '整理照片到半夜'],
    selfIntro: '很會抓角度，也很會抓人講話的小破綻。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_072',
    nameId: 'melody',
    displayName: 'Melody',
    age: 29,
    heightCm: 163,
    city: '台北',
    zodiac: '水瓶座',
    relationshipGoal: '慢慢認識',
    professionId: 'product_manager',
    professionLabel: '產品經理',
    photoId: 'practice_girl_072',
    personaId: 'cool_rational',
    personalityTags: ['理性', '節奏快', '觀察細'],
    interestTags: ['科技產品', '咖啡', '城市夜景'],
    lifestyleTags: ['開會很多', '下班散步', '週末整理生活'],
    selfIntro: '工作常在拆問題，聊天也喜歡有想法但不要太用力。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_073',
    nameId: 'noelle',
    displayName: 'Noelle',
    age: 25,
    heightCm: 158,
    city: '台中',
    zodiac: '金牛座',
    relationshipGoal: '想認真交往',
    professionId: 'pastry_chef',
    professionLabel: '甜點師',
    photoId: 'practice_girl_073',
    personaId: 'slow_worker',
    personalityTags: ['溫柔', '慢熟', '手作派'],
    interestTags: ['甜點', '烘焙', '老派咖啡'],
    lifestyleTags: ['早起備料', '試做新口味', '下班散步'],
    selfIntro: '做甜點很需要耐心，感情也是慢慢發酵比較好。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_074',
    nameId: 'sasha',
    displayName: 'Sasha',
    age: 24,
    heightCm: 160,
    city: '新北',
    zodiac: '雙子座',
    relationshipGoal: '先當朋友',
    professionId: 'pet_groomer',
    professionLabel: '寵物美容師',
    photoId: 'practice_girl_074',
    personaId: 'playful_extrovert',
    personalityTags: ['活潑', '好聊', '有耐心'],
    interestTags: ['寵物', '拍照', '甜點'],
    lifestyleTags: ['幫毛孩洗剪', '下班吃甜食', '假日去公園'],
    selfIntro: '工作每天被毛孩療癒，也每天被牠們考驗耐心。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_075',
    nameId: 'gloria',
    displayName: 'Gloria',
    age: 26,
    heightCm: 165,
    city: '桃園',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'bank_staff',
    professionLabel: '銀行行員',
    photoId: 'practice_girl_075',
    personaId: 'clear_boundaries',
    personalityTags: ['穩', '細心', '慢慢觀察'],
    interestTags: ['理財', '瑜珈', '小旅行'],
    lifestyleTags: ['規律下班', '週末小旅行', '下班伸展'],
    selfIntro: '我不是難聊，只是比較看重舒服跟尊重。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_076',
    nameId: 'rachel',
    displayName: 'Rachel',
    age: 28,
    heightCm: 168,
    city: '台北',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'stylist',
    professionLabel: '造型師',
    photoId: 'practice_girl_076',
    personaId: 'teasing_humor',
    personalityTags: ['有主見', '嘴利', '審美強'],
    interestTags: ['穿搭', '選物', '夜景散步'],
    lifestyleTags: ['幫客人搭造型', '逛選品店', '拍穿搭照'],
    selfIntro: '職業病是看穿搭，聊天太無聊我也會想幫你重搭。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_077',
    nameId: 'bonnie',
    displayName: 'Bonnie',
    age: 31,
    heightCm: 162,
    city: '台南',
    zodiac: '巨蟹座',
    relationshipGoal: '慢慢認識',
    professionId: 'civil_servant',
    professionLabel: '公務員',
    photoId: 'practice_girl_077',
    personaId: 'slow_worker',
    personalityTags: ['安定', '慢熱', '務實'],
    interestTags: ['小吃', '散步', '家庭料理'],
    lifestyleTags: ['規律上下班', '騎車通勤', '週末市場採買'],
    selfIntro: '生活不花俏，但喜歡把日子過得舒服穩定。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_078',
    nameId: 'leah',
    displayName: 'Leah',
    age: 27,
    heightCm: 164,
    city: '新竹',
    zodiac: '天秤座',
    relationshipGoal: '想認真交往',
    professionId: 'occupational_therapist',
    professionLabel: '職能治療師',
    photoId: 'practice_girl_078',
    personaId: 'clear_boundaries',
    personalityTags: ['溫暖', '專注', '有界線'],
    interestTags: ['手作', '散步', '心理學'],
    lifestyleTags: ['陪個案訓練', '下班公園走路', '週末做手作'],
    selfIntro: '工作需要同理心，但私下也很需要被好好尊重。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_079',
    nameId: 'gigi',
    displayName: 'Gigi',
    age: 26,
    heightCm: 167,
    city: '高雄',
    zodiac: '射手座',
    relationshipGoal: '開放看看',
    professionId: 'fitness_coach',
    professionLabel: '健身教練',
    photoId: 'practice_girl_079',
    personaId: 'playful_extrovert',
    personalityTags: ['陽光', '直爽', '會帶氣氛'],
    interestTags: ['健身', '海邊', '健康料理'],
    lifestyleTags: ['帶課訓練', '假日曬太陽', '揪朋友走路'],
    selfIntro: '比起硬聊，我比較喜歡一起動起來再慢慢熟。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_080',
    nameId: 'sylvia',
    displayName: 'Sylvia',
    age: 30,
    heightCm: 166,
    city: '台中',
    zodiac: '摩羯座',
    relationshipGoal: '慢慢認識',
    professionId: 'interior_designer',
    professionLabel: '空間設計師',
    photoId: 'practice_girl_080',
    personaId: 'cool_rational',
    personalityTags: ['沉穩', '美感控', '理性'],
    interestTags: ['空間設計', '老屋', '咖啡'],
    lifestyleTags: ['跑工地', '看材料', '假日看老屋'],
    selfIntro: '我對空間很挑，對相處也喜歡清楚舒服。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_081',
    nameId: 'aileen',
    displayName: 'Aileen',
    age: 32,
    heightCm: 163,
    city: '台北',
    zodiac: '天蠍座',
    relationshipGoal: '想認真交往',
    professionId: 'florist',
    professionLabel: '花藝師',
    photoId: 'practice_girl_081',
    personaId: 'clear_boundaries',
    personalityTags: ['成熟', '溫柔', '有界線'],
    interestTags: ['花藝', '市場散步', '老屋咖啡'],
    lifestyleTags: ['清晨進花', '整理花材', '晚上早睡'],
    selfIntro: '花可以很浪漫，但相處還是要有分寸跟誠意。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_082',
    nameId: 'june',
    displayName: 'June',
    age: 23,
    heightCm: 157,
    city: '台南',
    zodiac: '雙子座',
    relationshipGoal: '開放看看',
    professionId: 'illustrator',
    professionLabel: '插畫師',
    photoId: 'practice_girl_082',
    personaId: 'teasing_humor',
    personalityTags: ['古靈精怪', '愛吐槽', '靈感跳'],
    interestTags: ['插畫', '獨立漫畫', '小吃'],
    lifestyleTags: ['接案畫圖', '老屋工作', '晚上找宵夜'],
    selfIntro: '我畫圖很慢，但吐槽通常很快。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_083',
    nameId: 'tara',
    displayName: 'Tara',
    age: 28,
    heightCm: 165,
    city: '新北',
    zodiac: '射手座',
    relationshipGoal: '先當朋友',
    professionId: 'hair_stylist',
    professionLabel: '髮型設計師',
    photoId: 'practice_girl_083',
    personaId: 'playful_extrovert',
    personalityTags: ['外向', '手很巧', '會聊天'],
    interestTags: ['髮型', '穿搭', '甜點'],
    lifestyleTags: ['幫客人剪染', '下班逛街', '假日吃甜點'],
    selfIntro: '工作每天聊天，但私下也想遇到真的好聊的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_084',
    nameId: 'lina',
    displayName: 'Lina',
    age: 26,
    heightCm: 162,
    city: '桃園',
    zodiac: '摩羯座',
    relationshipGoal: '慢慢認識',
    professionId: 'data_analyst',
    professionLabel: '數據分析師',
    photoId: 'practice_girl_084',
    personaId: 'cool_rational',
    personalityTags: ['理性', '慢熱', '細節控'],
    interestTags: ['數據', '咖啡', '解謎遊戲'],
    lifestyleTags: ['通勤上班', '下班看報表', '週末解謎'],
    selfIntro: '我對數字很敏感，對人的節奏也會慢慢觀察。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_085',
    nameId: 'becky',
    displayName: 'Becky',
    age: 25,
    heightCm: 160,
    city: '新竹',
    zodiac: '巨蟹座',
    relationshipGoal: '慢慢認識',
    professionId: 'language_tutor',
    professionLabel: '語言家教',
    photoId: 'practice_girl_085',
    personaId: 'slow_worker',
    personalityTags: ['安靜', '耐心', '慢熟'],
    interestTags: ['語言', '手帳', '咖啡'],
    lifestyleTags: ['備課', '圖書館讀書', '慢慢回訊息'],
    selfIntro: '教人講話很有耐心，但自己熟起來需要一點時間。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_086',
    nameId: 'demi',
    displayName: 'Demi',
    age: 27,
    heightCm: 166,
    city: '高雄',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'mixologist',
    professionLabel: '調飲吧台',
    photoId: 'practice_girl_086',
    personaId: 'teasing_humor',
    personalityTags: ['俐落', '會接梗', '嘴甜帶刺'],
    interestTags: ['調飲', '夜景', '音樂'],
    lifestyleTags: ['晚班吧台', '白天補眠', '下班吃宵夜'],
    selfIntro: '我很會調味，也很會聽出一句話是不是太油。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_087',
    nameId: 'mabel',
    displayName: 'Mabel',
    age: 30,
    heightCm: 164,
    city: '台中',
    zodiac: '處女座',
    relationshipGoal: '想認真交往',
    professionId: 'social_worker',
    professionLabel: '社工',
    photoId: 'practice_girl_087',
    personaId: 'clear_boundaries',
    personalityTags: ['溫暖', '堅定', '重界線'],
    interestTags: ['散步', '心理學', '家常菜'],
    lifestyleTags: ['跑訪視', '寫紀錄', '下班放空'],
    selfIntro: '工作讓我很懂同理，但也更知道界線很重要。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_088',
    nameId: 'joan',
    displayName: 'Joan',
    age: 29,
    heightCm: 161,
    city: '台南',
    zodiac: '金牛座',
    relationshipGoal: '慢慢認識',
    professionId: 'bookstore_staff',
    professionLabel: '獨立書店店員',
    photoId: 'practice_girl_088',
    personaId: 'slow_worker',
    personalityTags: ['溫吞', '文靜', '有自己的節奏'],
    interestTags: ['獨立書店', '老屋', '茶'],
    lifestyleTags: ['整理書架', '老屋工作', '晚上泡茶'],
    selfIntro: '日子慢一點也很好，聊天也想慢慢讀懂對方。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_089',
    nameId: 'cora',
    displayName: 'Cora',
    age: 24,
    heightCm: 163,
    city: '台北',
    zodiac: '水瓶座',
    relationshipGoal: '開放看看',
    professionId: 'indie_musician',
    professionLabel: '獨立樂團貝斯手',
    photoId: 'practice_girl_089',
    personaId: 'teasing_humor',
    personalityTags: ['有個性', '嘴硬', '反應快'],
    interestTags: ['獨立音樂', '貝斯', '深夜食堂'],
    lifestyleTags: ['排練', '寫歌', '下班找宵夜'],
    selfIntro: '不一定秒回，但回了通常不會太無聊。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_090',
    nameId: 'talia',
    displayName: 'Talia',
    age: 28,
    heightCm: 167,
    city: '花蓮',
    zodiac: '天秤座',
    relationshipGoal: '慢慢認識',
    professionId: 'inn_host',
    professionLabel: '旅宿管家',
    photoId: 'practice_girl_090',
    personaId: 'clear_boundaries',
    personalityTags: ['自然', '溫和', '有分寸'],
    interestTags: ['海邊', '小旅行', '手沖咖啡'],
    lifestyleTags: ['接待旅人', '整理房務', '海邊散步'],
    selfIntro: '每天聽很多旅人的故事，但自己的故事想慢慢說。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_091',
    nameId: 'erin',
    displayName: 'Erin',
    age: 33,
    heightCm: 165,
    city: '台北',
    zodiac: '摩羯座',
    relationshipGoal: '想認真交往',
    professionId: 'hr_consultant',
    professionLabel: '人資顧問',
    photoId: 'practice_girl_091',
    personaId: 'clear_boundaries',
    personalityTags: ['成熟', '會觀察人', '重分寸'],
    interestTags: ['職涯', '紅酒課', '城市散步'],
    lifestyleTags: ['面談很多', '下班散步', '週末整理生活'],
    selfIntro: '工作看很多人，私下更重視真誠和邊界。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_092',
    nameId: 'nami',
    displayName: 'Nami',
    age: 26,
    heightCm: 158,
    city: '高雄',
    zodiac: '處女座',
    relationshipGoal: '慢慢認識',
    professionId: 'pharmacist',
    professionLabel: '藥師',
    photoId: 'practice_girl_092',
    personaId: 'clear_boundaries',
    personalityTags: ['細心', '有原則', '溫和'],
    interestTags: ['健康知識', '咖啡', '慢跑'],
    lifestyleTags: ['藥局輪班', '下班慢跑', '週末喝咖啡'],
    selfIntro: '工作很講精準，相處也喜歡清楚不壓迫。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_093',
    nameId: 'roxy',
    displayName: 'Roxy',
    age: 25,
    heightCm: 162,
    city: '台北',
    zodiac: '雙子座',
    relationshipGoal: '開放看看',
    professionId: 'podcast_editor',
    professionLabel: 'Podcast 剪輯',
    photoId: 'practice_girl_093',
    personaId: 'teasing_humor',
    personalityTags: ['嘴快', '愛接梗', '聽感敏銳'],
    interestTags: ['Podcast', '喜劇', '深夜咖啡'],
    lifestyleTags: ['剪音檔', '聽節目', '晚上靈感多'],
    selfIntro: '我很會剪掉冷場，但聊天冷掉我不一定救。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_094',
    nameId: 'queenie',
    displayName: 'Queenie',
    age: 28,
    heightCm: 166,
    city: '台中',
    zodiac: '牡羊座',
    relationshipGoal: '開放看看',
    professionId: 'chef',
    professionLabel: '餐廚主廚',
    photoId: 'practice_girl_094',
    personaId: 'teasing_humor',
    personalityTags: ['直爽', '反應快', '有主見'],
    interestTags: ['料理', '市場', '宵夜'],
    lifestyleTags: ['餐期很忙', '研發菜色', '晚下班吃宵夜'],
    selfIntro: '廚房節奏很快，聊天太慢我可能會先吐槽。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_095',
    nameId: 'ela',
    displayName: 'Ela',
    age: 27,
    heightCm: 160,
    city: '嘉義',
    zodiac: '雙魚座',
    relationshipGoal: '慢慢認識',
    professionId: 'librarian',
    professionLabel: '圖書館員',
    photoId: 'practice_girl_095',
    personaId: 'slow_worker',
    personalityTags: ['安靜', '溫柔', '慢熟'],
    interestTags: ['閱讀', '茶', '老街散步'],
    lifestyleTags: ['整理館藏', '午後喝茶', '慢慢回訊息'],
    selfIntro: '我喜歡安靜的人，也喜歡不急著定義的關係。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_096',
    nameId: 'willa',
    displayName: 'Willa',
    age: 30,
    heightCm: 164,
    city: '台南',
    zodiac: '金牛座',
    relationshipGoal: '想認真交往',
    professionId: 'ceramic_artist',
    professionLabel: '陶藝創作者',
    photoId: 'practice_girl_096',
    personaId: 'slow_worker',
    personalityTags: ['耐心', '手作派', '慢熱'],
    interestTags: ['陶藝', '老屋', '手沖咖啡'],
    lifestyleTags: ['拉坯修坯', '逛老屋', '晚上慢煮'],
    selfIntro: '做陶很急不來，喜歡穩穩靠近的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_097',
    nameId: 'hana',
    displayName: 'Hana',
    age: 24,
    heightCm: 165,
    city: '台東',
    zodiac: '射手座',
    relationshipGoal: '先當朋友',
    professionId: 'surf_instructor',
    professionLabel: '衝浪教練',
    photoId: 'practice_girl_097',
    personaId: 'playful_extrovert',
    personalityTags: ['陽光', '直率', '愛冒險'],
    interestTags: ['衝浪', '海邊', '日出'],
    lifestyleTags: ['看浪況', '帶初學者', '曬太陽'],
    selfIntro: '人生已經夠忙了，聊天希望輕鬆一點、好笑一點。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_098',
    nameId: 'penny',
    displayName: 'Penny',
    age: 27,
    heightCm: 163,
    city: '新北',
    zodiac: '獅子座',
    relationshipGoal: '開放看看',
    professionId: 'dance_teacher',
    professionLabel: '舞蹈老師',
    photoId: 'practice_girl_098',
    personaId: 'playful_extrovert',
    personalityTags: ['有活力', '會帶氣氛', '大方'],
    interestTags: ['跳舞', '音樂', '街頭小吃'],
    lifestyleTags: ['排課練舞', '下課吃宵夜', '週末表演'],
    selfIntro: '我節奏感很好，但聊天不要只有我一個人在帶拍。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_099',
    nameId: 'audrey',
    displayName: 'Audrey',
    age: 31,
    heightCm: 168,
    city: '台北',
    zodiac: '水瓶座',
    relationshipGoal: '想認真交往',
    professionId: 'architect',
    professionLabel: '建築師',
    photoId: 'practice_girl_099',
    personaId: 'cool_rational',
    personalityTags: ['沉穩', '有想法', '標準高'],
    interestTags: ['建築', '城市散步', '展覽'],
    lifestyleTags: ['畫圖審圖', '看模型', '找城市細節'],
    selfIntro: '我喜歡有結構的東西，也喜歡有邊界的人。',
  ),
  PracticeGirlProfile(
    profileId: 'practice_girl_100',
    nameId: 'skye',
    displayName: 'Skye',
    age: 29,
    heightCm: 162,
    city: '新竹',
    zodiac: '天蠍座',
    relationshipGoal: '慢慢認識',
    professionId: 'ux_researcher',
    professionLabel: 'UX 研究員',
    photoId: 'practice_girl_100',
    personaId: 'cool_rational',
    personalityTags: ['觀察細', '理性', '慢熱'],
    interestTags: ['使用者研究', '咖啡', '紀錄片'],
    lifestyleTags: ['訪談整理', '貼便利貼', '晚上看紀錄片'],
    selfIntro: '我很會觀察細節，所以也很容易看出對方是不是用心。',
  ),
];
